module = { SOI ~ stream ~ EOI }
stream = { (import | definitions | impls)* }

impls  = { implementation }
import = { c_import | niebo_import }

c_import      = { "header" ~ path ~ ";" }
niebo_import  = { "use" ~ path ~ ";" }
use_statement = { "use" ~ path ~ ";" }

visibility = { "pub" | "module" }

definitions = { definition }

definition = { visibility? ~ (fn_definition | fn_declaration | type_definition | const_definition | trait_definition | module_definition) }

implementation = {
    "impl" ~ path ~ "{" ~ fn_definition* ~ "}"
}

trait_definition = { "trait" ~ identifier ~ template_def? ~ "{" ~ trait_body* ~ "}" }
trait_body       = {
    type_definition
  | fn_definition
  | type_declaration ~ ";"
  | fn_declaration ~ ";"
}

type_declaration = { "type" ~ identifier }
type_definition  = { type_declaration ~ "=" ~ path ~ ";" }

fn_declaration = { "const"? ~ "fn" ~ identifier ~ template_def? ~ "(" ~ params? ~ ")" ~ ("->" ~ type_expr)? }
fn_definition  = { fn_declaration ~ block_expression }

module_definition = { "mod" ~ identifier ~ (";" | ("{" ~ stream ~ "}")) }

block_expression = { "{" ~ statement* ~ "}" }

statement = {
    import
  | use_statement
  | let_declaration
  | const_definition
  | break_statement
  | continue_statement
  | expression ~ ";"?
}

expression = {
    (if_expression | literal_expression | while_expression | for_expression | match_expression | loop_expression | return_expression | block_expression | prefix_unary_operation_expression | path ) ~ expression_postfix?
}

prefix_unary_operation_expression = { prefix_unary_operator ~ expression }
prefix_unary_operator             = { "-" | "!" | "++" | "--" | "*" | "&" }

if_expression    = { "if" ~ expression ~ block_expression ~ ("else" ~ (if_expression | block_expression))? }
while_expression = { "while" ~ expression ~ "do" ~ block_expression }
for_expression   = { "for" ~ identifier ~ "in" ~ expression ~ block_expression }
match_expression = { "match" ~ expression ~ "{" ~ match_arm* ~ "}" }
match_arm        = { pattern ~ "=>" ~ (block_expression | expression) ~ ","? }
pattern          = { identifier | path | number | string | "_" }

loop_expression    = { "loop" ~ block_expression }
return_expression  = { "return" ~ expression? }
break_statement    = { "break" ~ ";" }
continue_statement = { "continue" ~ ";" }

expression_postfix = {
    assignment_expression_postfix
  | call_postfix
  | postfix_unary_operator
  | binary_expression_postfix
  | member_access_postfix
}

member_access_postfix = {"." ~ identifier}

postfix_unary_operator = { "?" | "++" | "--" }

assignment_expression_postfix = { "=" ~ expression }

binary_expression_postfix = {
    boolean_or
  | boolean_and
  | boolean_eq
  | boolean_neq
  | boolean_leq
  | boolean_geq
  | boolean_le
  | boolean_ge
  | bitwise_and
  | bitwise_or
  | arithmetic_add
  | arithmetic_sub
  | arithmetic_mul
  | arithmetic_div
  | arithmetic_mod
}

boolean_or  = { "||" ~ expression }
boolean_and = { "&&" ~ expression }
boolean_eq  = { "==" ~ expression }
boolean_neq = { "!=" ~ expression }
boolean_leq = { "<=" ~ expression }
boolean_geq = { ">=" ~ expression }
boolean_le  = { "<" ~ expression }
boolean_ge  = { ">" ~ expression }

bitwise_and = { "&" ~ expression }
bitwise_or  = { "|" ~ expression }

arithmetic_add = { "+" ~ expression }
arithmetic_sub = { "-" ~ expression }
arithmetic_mul = { "*" ~ expression }
arithmetic_div = { "/" ~ expression }
arithmetic_mod = { "%" ~ expression }

call_postfix = { "(" ~ call_params? ~ ")" }
call_params  = { (expression ~ ",")* ~ expression ~ ","? }

let_declaration  = { "let" ~ mutable_modifier? ~ identifier ~ (":" ~ type_expr)? ~ "=" ~ expression ~ ";" }
mutable_modifier = { "mut" }

const_definition = { "const" ~ identifier ~ (":" ~ type_expr)? ~ "=" ~ expression ~ ";" }

params  = { (param ~ ",")* ~ param ~ ","? ~ varidic? }
param   = { identifier ~ ":" ~ type_expr }
varidic = { "..." }

path       =  { rel_path? ~ ident_root ~ ("::" ~ ident_root)* }
rel_path   =  { "global::" | (("super" | "crate") ~ "::")+ }
ident_root =  { identifier ~ template_spec? }
identifier = @{ (ASCII_ALPHA | "_") ~ identifier_elements* }

template_spec = { "<" ~ (path ~ ",")* ~ path ~ ","? ~ ">" }

template_def   = { "<" ~ (template_ident ~ ",")* ~ template_ident ~ ","? ~ ">" }
template_ident = { identifier ~ ":" ~ (path ~ "+")* ~ path }

type_expr = {
    primitive_type
  | path
  | identifier
  | function_type
  | array_type
  | mutable_pointer_type
  | pointer_type
  | mutable_reference_type
  | reference_type
  | struct_type
  | union_type
  | variant_type
  | template_type
  | "(" ~ type_expr ~ ")"
}

function_type = { "fn" ~ "(" ~ type_params? ~ ")" ~ ("->" ~ type_expr)? }
type_params   = { (type_expr ~ ",")* ~ type_expr ~ ","? }

array_type             = { "[" ~ type_expr ~ "]" }
pointer_type           = { "*" ~ type_expr }
mutable_pointer_type   = { "*" ~ "mut" ~ type_expr }
reference_type         = { "&" ~ type_expr }
mutable_reference_type = { "&" ~ "mut" ~ type_expr }

struct_type   = { "struct" ~ "{" ~ struct_member* ~ "}" }
union_type    = { "union" ~ "{" ~ struct_member* ~ "}" }
variant_type  = { "variant" ~ "{" ~ struct_member* ~ "}" }
struct_member = { identifier ~ ":" ~ type_expr ~ ","? }

template_type      = { "template" ~ "<" ~ (identifier ~ ",")* ~ identifier ~ ","? ~ ">" }
primitive_type     = { int_type | uint_type | float_type | "bool" | "int" | "uint" | "float" | "string" | "void" }
int_type           = { "i" ~ ASCII_DIGIT+ }
uint_type          = { "u" ~ ASCII_DIGIT+ }
float_type         = { "float" ~ ASCII_DIGIT+ }
literal_expression = { number | string }

number       = @{ (ASCII_DIGIT+ ~ "." ~ ASCII_DIGIT* ~ float_suffix?) | (ASCII_DIGIT+ ~ int_suffix?) }
int_suffix   =  { ("i" | "u") ~ ASCII_DIGIT+ }
float_suffix =  { "f" ~ ASCII_DIGIT+ }
string       = @{
    "\"" ~ ("\\\"" | "\\\\" | "\\n" | "\\r" | "\\t" | "\\0" | "\\x" ~ ASCII_HEX_DIGIT{2} | "\\u" ~ "{" ~ ASCII_HEX_DIGIT+ ~ "}" | (!"\"" ~ ANY))* ~ "\""
}
symbol       = @{ ANY }

identifier_elements = { ASCII_ALPHANUMERIC | "_" }

keyword = {
    "type"
  | "mod"
  | "fn"
  | "trait"
  | "let"
  | "const"
  | "mut"
  | "pub"
  | "module"
  | "for"
  | "in"
  | "while"
  | "if"
  | "else"
  | "loop"
  | "match"
  | "use"
  | "header"
  | "break"
  | "continue"
  | "return"
  | "struct"
  | "union"
  | "variant"
  | "template"
  | "bool"
  | "int"
  | "uint"
  | "float"
  | "string"
  | "void"
}

COMMENT    = _{ ("/*" ~ ANY* ~ "*/") | ("//" ~ ANY* ~ "\n") }
WHITESPACE = _{ " " | "\n" | "\t" }
