module = { SOI ~ stream ~ EOI }
stream = { (import | definition | impls)* }

impls  = { implementation | trait_implementation }
import = { c_import | niebo_import }

c_import      = { "header" ~ import_path ~ ";" }
niebo_import  = { "import" ~ import_path ~ ";" }
use_statement = { "use" ~ identifier ~ "as" ~ path ~ ";" }

visibility = { "pub" | "module" }

definition = { visibility? ~ (fn_definition | fn_declaration | type_declaration | type_definition | const_definition | trait_definition | module_definition) }

implementation = {
    "methods" ~ path ~ "{" ~ fn_definition* ~ "}"
}

trait_implementation = {
    "extend" ~ path ~ "as" ~ path ~ "{" ~ fn_definition* ~ "}"
}

trait_definition = { "inter" ~ identifier ~ template_def? ~ "{" ~ trait_body* ~ "}" }
trait_body       = {
    type_definition
  | fn_definition
  | type_declaration ~ ";"
  | fn_declaration ~ ";"
}

struct_declaration  = {"struct" ~ identifier}
union_declaration   = {"union" ~ identifier}
variant_declaration = {"variant" ~ identifier}
alias_declaration   = {"type" ~ identifier}

struct_definition  = { "struct" ~ identifier ~ "{" ~ params ~ "}" }
union_definition   = { union_declaration ~ "{" ~ params ~ "}" }
variant_definition = { variant_declaration ~ "{" ~ params ~ "}" }
alias_definition   = {"type" ~ identifier ~ "=" ~ type_expr ~ ";"}

type_declaration = { (struct_declaration | union_declaration | variant_declaration | alias_declaration) ~ ";"}
type_definition = { struct_definition | union_definition | variant_definition | alias_definition }

fn_declaration = { "const"? ~ "fn" ~ identifier ~ template_def? ~ "(" ~ params? ~ ")" ~ ("->" ~ type_expr)? }
fn_definition  = { fn_declaration ~ block_expression }

module_definition = { "mod" ~ identifier ~ (";" | ("{" ~ stream ~ "}")) }

block_expression = { "{" ~ statement* ~ "}" }

return_statement   = { "return" ~ expression? }
value_statement    = { "value" ~ expression? }


statement = {
    (import ~ ";")
  | (use_statement ~ ";")
  | (let_declaration ~ ";")
  | (const_definition ~ ";")
  | (break_statement ~ ";")
  | (continue_statement ~ ";")
  | (return_statement  ~ ";")
  | (value_statement  ~ ";")
  | (continue_statement ~ ";")
  | expression ~ ";"?
}

expression_priority = { "(" ~ expression ~ ")" }
expression = {
    (expression_priority  | intrinsic_expression | struct_expression | if_expression | literal_expression | while_expression | for_expression | match_expression | loop_expression |  block_expression | prefix_unary_operation_expression | path ) ~ expression_postfix*
}

prefix_unary_operation_expression = { prefix_unary_operator ~ expression }
prefix_unary_operator             = { "-" | "!" | "++" | "--" | "*" | "&" }

intrinsic_expression = { "@" ~ identifier ~ "(" ~ call_params? ~ ")" }
if_expression       = { "if" ~ expression ~ block_expression ~ ("else" ~ (if_expression | block_expression))? }
while_expression    = { ( identifier ~ ":" )? ~ "while" ~ expression ~ block_expression }
for_expression      = { ( identifier ~ ":" )? ~ "for" ~ identifier ~ "in" ~ expression ~ block_expression }
match_expression    = { "match" ~ expression ~ "{" ~ match_arm* ~ "}" }
match_arm           = { pattern ~ "=>" ~ (block_expression | expression) ~ ","? }
pattern             = { identifier | path | number | string | "_" }

loop_expression    = { ( identifier ~ ":" )? ~ "loop" ~  block_expression }

struct_named_field = { identifier ~ ":" ~ expression }
struct_expression  = { path ~ "{" ~  (struct_named_field ~ ",")* ~ struct_named_field? ~ "}"}

break_statement    = { "break" ~ identifier? }
continue_statement = { "continue" ~ identifier? }

expression_postfix = {
    assignment_expression_postfix
  | call_postfix
  | index_access_postfix
  | unary_expression_postfix
  | binary_expression_postfix
  | member_access_postfix
}

member_access_postfix = {"." ~ identifier }
index_access_postfix = {"[" ~ expression ~ "]" }

unary_return_error_postfix = { "?" }
unary_increase_postfix = { "++" }
unary_decrease_postfix = { "--" }

unary_expression_postfix = { 
    unary_return_error_postfix
  | unary_increase_postfix
  | unary_decrease_postfix
}

assignment_expression_postfix = { "=" ~ expression }

binary_expression_postfix = {
    boolean_or
  | boolean_and
  | boolean_eq
  | boolean_neq
  | boolean_leq
  | boolean_geq
  | boolean_le
  | boolean_ge
  | bitwise_and
  | bitwise_or
  | bitwise_xor
  | arithmetic_add
  | arithmetic_sub
  | arithmetic_mul
  | arithmetic_div
  | arithmetic_mod
}

boolean_or  = { "||" ~ expression }
boolean_and = { "&&" ~ expression }
boolean_eq  = { "==" ~ expression }
boolean_neq = { "!=" ~ expression }
boolean_leq = { "<=" ~ expression }
boolean_geq = { ">=" ~ expression }
boolean_le  = { "<" ~ expression }
boolean_ge  = { ">" ~ expression }

bitwise_and = { "&" ~ expression }
bitwise_or  = { "|" ~ expression }
bitwise_xor = { "~" ~ expression }

arithmetic_add = { "+" ~ expression }
arithmetic_sub = { "-" ~ expression }
arithmetic_mul = { "*" ~ expression }
arithmetic_div = { "/" ~ expression }
arithmetic_mod = { "%" ~ expression }

assignment_bitwise_and = { "&=" ~ expression }
assignment_bitwise_or  = { "|=" ~ expression }
assignment_bitwise_xor = { "~=" ~ expression }
assignment_arithmetic_add = { "+=" ~ expression }
assignment_arithmetic_sub = { "-=" ~ expression }
assignment_arithmetic_mul = { "*=" ~ expression }
assignment_arithmetic_div = { "/=" ~ expression }
assignment_arithmetic_mod = { "%=" ~ expression }


call_postfix = { "(" ~ call_params? ~ ")" }
call_params  = { (expression ~ ",")* ~ expression ~ ","? }

let_declaration  = { "let" ~ mutable_modifier? ~ identifier ~ (":" ~ type_expr)? ~ "=" ~ expression }
mutable_modifier = { "mut" }

const_definition = { "const" ~ identifier ~ (":" ~ type_expr)? ~ "=" ~ expression }

params  = { (param ~ ",")* ~ param?  }
param   = { identifier ~ ":" ~ type_expr }
varidic = { "..." }

import_path = { grouped_import_path | path }
grouped_import_path = { path ~ "::" ~ import_group }
import_group = { "{" ~ (ident_root ~ ",")* ~ ident_root? ~ "}" }

path       =  { rel_path? ~ ident_root ~ ("::" ~ ident_root)* }
rel_path   =  { "global::" | (("super" | "project") ~ "::")+ }
ident_root =  { identifier ~ template_spec? }
identifier = @{ (ASCII_ALPHA | "_") ~ identifier_elements* }

template_spec = { "<" ~ (path ~ ",")* ~ path ~ ","? ~ ">" }

template_def   = { "<" ~ (template_ident ~ ",")* ~ template_ident ~ ","? ~ ">" }
template_ident = { identifier ~ ":" ~ (path ~ "+")* ~ path }

type_expr = {
    primitive_type
  | function_type
  | array_type
  | mutable_pointer_type
  | pointer_type
  | mutable_reference_type
  | reference_type
  | template_type
  | path
  | "(" ~ type_expr ~ ")"
}

function_type = { "fn" ~ "(" ~ type_params? ~ ")" ~ ("->" ~ type_expr)? }
type_params   = { (type_expr ~ ",")* ~ type_expr ~ ","? }

array_type             = { "[" ~ type_expr ~ "]" }
pointer_type           = { "*" ~ type_expr }
mutable_pointer_type   = { "*" ~ "mut" ~ type_expr }
reference_type         = { "&" ~ type_expr }
mutable_reference_type = { "&" ~ "mut" ~ type_expr }


template_type      =  { "template" ~ "<" ~ (identifier ~ ",")* ~ identifier ~ ","? ~ ">" }
primitive_type     =  { int_type | uint_type | float_type | "bool" | "int" | "uint" | "float" | "string" | "void" }
prec               = @{ASCII_DIGIT+}
int_type           =  { "i" ~ prec }
uint_type          =  { "u" ~ prec }
float_type         =  { "f" ~ prec }
literal_expression =  { number | string }

number       = @{ (ASCII_DIGIT+ ~ "." ~ ASCII_DIGIT* ~ float_suffix?) | (ASCII_DIGIT+ ~ int_suffix?) }
int_suffix   =  { ("i" | "u") ~ ASCII_DIGIT+ }
float_suffix =  { "f" ~ ASCII_DIGIT+ }
string       = @{
    "\"" ~ ("\\\"" | "\\\\" | "\\n" | "\\r" | "\\t" | "\\0" | "\\x" ~ ASCII_HEX_DIGIT{2} | "\\u" ~ "{" ~ ASCII_HEX_DIGIT+ ~ "}" | (!"\"" ~ ANY))* ~ "\""
}
symbol       = @{ ANY }

identifier_elements = { ASCII_ALPHANUMERIC | "_" }

keyword = {
    "type"
  | "mod"
  | "fn"
  | "inter"
  | "let"
  | "const"
  | "mut"
  | "pub"
  | "module"
  | "for"
  | "in"
  | "while"
  | "if"
  | "else"
  | "loop"
  | "match"
  | "use"
  | "methods"
  | "extend"
  | "as"
  | "header"
  | "break"
  | "continue"
  | "return"
  | "struct"
  | "union"
  | "variant"
  | "template"
  | "bool"
  | "int"
  | "uint"
  | "float"
  | "string"
  | "void"
}

COMMENT    = _{ ("/*" ~ ANY* ~ "*/") | ("//" ~ ANY* ~ "\n") }
WHITESPACE = _{ " " | "\n" | "\t" }
